<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class SalesOrderOutstanding extends Model
{
    protected $fillable = [
        'bu',
        'manager_ax',
        'manager_name',
        'so_eks',
        'so_amount',
        'so_nett',
        'swa',
        'jenis_so',
        'sales_id',
        'sales_responsible',
        'sales_status',
        'sales_unit_id',
        'agr_sales_resp_name',
        'created_date_time1',
        'dimension',
        'dimension2_',
        'dimension3_',
        'tcn_sotype',
        'approval_status',
        'customer_ref',
        'purch_order_form_num',
        'dataareaid',
        'recid',
        'dataareaid_2',
        'item_id',
        'qty_ordered',
        'sales_price',
        'line_disc',
        'sales_group',
        'line_amount',
        'invent_dim_id',
        'line_percent',
        'dataareaid_3',
        'account_num',
        'agr_school_id',
        'dataareaid_4',
        'item_name',
        'agr_pengarang',
        'agr_brand_name',
        'agr_grade_name',
        'agr_item_curriculum',
        'agr_item_segment',
        'agr_publish_date',
        'agr_publish_year',
        'dataareaid_5',
        'qty',
        'status_issue',
        'dataareaid_6',
        'erl_invent_location_id',
    ];
}